### ISSUE TITLE
Feature Request: support for setting variables in synthetics test resource

### ISSUE THREAD

**Issue by albferrari** [DataDog/terraform-provider-datadog#664]
the synthetic test module allow to select browser test but it does not allow to configure steps for the browser test.

if you configure steps manually after the deploy and the steps include link to global variable the link is lost at the next deploy

**Comment by therve** [comment]
Hi,

Can you develop a bit? Is it related only to global variables? Which version are you using? Do you have a sample config? Thanks.

**Comment by albferrari** [comment]
I'm using terraform version 0.13.0 and datadog provider 2.12.1.

I'm only seeing this issue with global variable here my tf resource
`
resource "datadog_synthetics_test" "test_test" {
  type = "browser"

  request = {
    method = "GET"
    url    = "https://www.ontariosystems.com/"
  }

  device_ids = ["laptop_large"]
  locations  = ["aws:us-east-2", "aws:us-west-1"]

  options = {
    tick_every = 86400
  }

  name    = "TEST"
  message = <<EOF
  somethin is happening
  EOF
  tags    = ["env:prod", "time:business_hours"]

  status = "paused"
}
`

this test have some steps associated through the user interface but when any changes are re-deployed the global variable are not associated to the steps anymore
![image](https://user-images.githubusercontent.com/22177368/93349781-eb094680-f805-11ea-9ff2-cf2197951351.png)

the only way the test can be restored is by delete the reference to the variable and adding them back from the user interface

**Comment by therve** [comment]
We just released a version with browser steps support. Can you try upgrading and import your tests to see what happens? It's possible there is an issue with variables as well?

**Comment by albferrari** [comment]
the variable are still not working with the new version I check the output of the datadog rest api and the variables reference is store in the config node which is wiped by terraform
`
{
    "status": "paused",
    "public_id": "ejs-awh-djk",
    "tags": [
        "environment:prod",
        "time:business_hours"
    ],
    "locations": [
        "aws:us-east-2",
        "aws:us-west-1"
    ],
    "message": "{{#is_alert}}\nContact Savvy User Interface is not available \n@alberto.ferrari@ontariosystems.com\n{{/is_alert}}\n{{#is_recovery}}\nContact Savvy User Interface is available @alberto.ferrari@ontariosystems.com \n{{/is_recovery}}\n",
    "name": "CTSUI",
    "monitor_id": 21658363,
    "type": "browser",
    "steps": [
        {
            "name": "Type text on input \"CacheUserName\"",
            "noScreenshot": false,
            "allowFailure": false,
            "params": {
                "value": "{{ CTSUI_USERNAME }}",
                "element": {
                    "url": "https://cts.ontariosystems.cloud/oc/qc/cl.ui.Index.cls",
                    "targetOuterHTML": "<input class=\"form-control login-username\" type=\"text\" name=\"CacheUserName\" placeholder=\"Email\">",
                    "multiLocator": {
                        "ab": "/*[local-name()=\"html\"][1]/*[local-name()=\"body\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"form\"][1]/*[local-name()=\"input\"][1]",
                        "co": "[{\"text\":\"email\",\"textType\":\"placeholder\"}]",
                        "cl": "/descendant::*[contains(concat(' ', normalize-space(@class), ' '), \" unauthenticated-container \")]/descendant::*[contains(concat(' ', normalize-space(@class), ' '), \" login-username \")][1]",
                        "at": "/descendant::*[@name=\"CacheUserName\"]",
                        "clt": "/descendant::*[contains(concat(' ', normalize-space(@class), ' '), \" unauthenticated-container \")]/descendant::*[contains(concat(' ', normalize-space(@class), ' '), \" login-username \")][1]",
                        "ro": "//*[@name=\"CacheUserName\"]"
                    }
                }
            },
            "type": "typeText"
        },
        {
            "name": "Type text on input \"CachePassword\"",
            "noScreenshot": false,
            "allowFailure": false,
            "params": {
                "value": "{{ CTSUI_PASSWORD }}",
                "element": {
                    "url": "https://cts.ontariosystems.cloud/oc/qc/cl.ui.Index.cls",
                    "targetOuterHTML": "<input class=\"form-control login-password\" type=\"password\" name=\"CachePassword\" placeholder=\"Passwor",
                    "multiLocator": {
                        "ab": "/*[local-name()=\"html\"][1]/*[local-name()=\"body\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"form\"][1]/*[local-name()=\"input\"][2]",
                        "co": "[{\"text\":\"password\",\"textType\":\"placeholder\"}]",
                        "cl": "/descendant::*[contains(concat(' ', normalize-space(@class), ' '), \" login-password \")]",
                        "at": "/descendant::*[@name=\"CachePassword\"]",
                        "clt": "/descendant::*[contains(concat(' ', normalize-space(@class), ' '), \" login-password \")]",
                        "ro": "//*[@name=\"CachePassword\"]"
                    }
                }
            },
            "type": "typeText"
        },
        {
            "name": "Click on span \"Login\"",
            "noScreenshot": false,
            "allowFailure": false,
            "params": {
                "element": {
                    "url": "https://cts.ontariosystems.cloud/oc/qc/cl.ui.Index.cls",
                    "targetOuterHTML": "<span>Login</span>",
                    "multiLocator": {
                        "ab": "/*[local-name()=\"html\"][1]/*[local-name()=\"body\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"div\"][1]/*[local-name()=\"form\"][1]/*[local-name()=\"span\"][1]/*[local-name()=\"span\"][1]/*[local-name()=\"button\"][1]/*[local-name()=\"span\"][1]",
                        "co": "[{\"text\":\"login\",\"textType\":\"directText\"}]",
                        "cl": "/descendant::*[contains(concat(' ', normalize-space(@class), ' '), \" unauthenticated-container \")]/descendant::*[contains(concat(' ', normalize-space(@class), ' '), \" login \")][1]/*[local-name()=\"span\"][1]",
                        "at": "/descendant::*[@name=\"loginForm\"]/descendant::*[@type=\"submit\"]/*[local-name()=\"span\"][1]",
                        "clt": "/descendant::*[contains(concat(' ', normalize-space(@class), ' '), \" unauthenticated-container \")]/descendant::*[text()[normalize-space(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ', 'abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')) = \"login\"]]",
                        "ro": "//*[text()[normalize-space(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ', 'abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')) = \"login\"]]"
                    }
                }
            },
            "type": "click"
        }
    ],
    "config": {
        "variables": [
            {
                "type": "global",
                "name": "CTSUI_USERNAME",
                "id": "2c616f77-9855-49d4-86bb-eedbfdc3ccbf"
            },
            {
                "type": "global",
                "name": "CTSUI_PASSWORD",
                "id": "51a63a0a-60ca-4015-982b-5aa567cbea4e"
            }
        ],
        "request": {
            "url": "https://cts.ontariosystems.cloud/oc/qc/cl.ui.Index.cls",
            "method": "GET"
        },
        "assertions": []
    },
    "options": {
        "device_ids": [
            "laptop_large"
        ],
        "min_location_failed": 1,
        "tick_every": 300
    }
}
`

**Comment by therve** [comment]
Thanks for the details. I tested it, and the part behind wiped out is the `variables` section in the `config`. This isn't supported yet indeed.

**Comment by therve** [comment]
This has been done in #691 and released with 2.14. Let me know if it works for you!. Thanks.
