### ISSUE TITLE
Intermittent "Provider produced inconsistent result after apply" Error

### ISSUE THREAD

**Issue by bkimbrough88** [DataDog/terraform-provider-datadog#860]
### Terraform Version

 terraform -v
Terraform v0.13.6
+ provider registry.terraform.io/-/datadog v2.19.1
+ provider registry.terraform.io/datadog/datadog v2.19.1
+ provider registry.terraform.io/hashicorp/aws v3.24.1

### Affected Resource(s)

Please list the resources as a list, for example:

- module.synthetics_global_vars.datadog_synthetics_global_variable.platform_ocp_user
- module.openshift_alerts.datadog_monitor.trident_slow_operation
- module.openshift_dashboards.datadog_dashboard_list.ocp_dashboards
- module.openshift_alerts.datadog_monitor.trident_slow_vol_create_delete
- module.synthetics_global_vars.datadog_synthetics_global_variable.platform_ocp_pass
- module.openshift_alerts.datadog_monitor.pvc_pending

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

MAIN
```hcl
module "openshift_alerts" {
  source                        = "../../../modules/ocp-alerts"

  alerts_addresses              = var.alerts_addresses
  notifications_addresses       = var.notifications_addresses
  trident_volumes_dashboard_url = module.openshift_dashboards.trident_volumes_dashboard_url
}

module "synthetics_global_vars" {
  source    = "../../../modules/synthetics-global-vars"
}
```

openshift_alerts
```hcl
locals {
  common_tags = [
    "mute_on_agent_deploy",
    "app:ocp",
    "component:trident",
    "team:platform"
  ]
}


resource "datadog_monitor" "pvc_pending" {
  name = "PVC is stuck in Pending status in {{cluster_name.name}}"
  type = "metric alert"
  query = "avg(last_5m):min:kubernetes_state.persistentvolumeclaim.status{phase:pending} by {cluster_name,storageclass} >= ${var.pvc_pending_duration_thresholds.critical}"
  message = <<EOF
  A PVC has been in the pending status for over 5minutes. This can indicate a problem with volume provisioning (Trident) or a misconfiguration in the PVC definition itself.
  
  See the [Dashboard](${var.trident_volumes_dashboard_url}) for more information on the service's status and [Documentation](${var.trident_documentation_url}) for troubleshooting steps.
  
  {{#is_alert}}${join(" ", var.notifications_addresses)}{{/is_alert}}
  {{#is_alert_recovery}}${join(" ", var.notifications_addresses)}{{/is_alert_recovery}}
  EOF
  notify_audit         = false
  locked               = false
  timeout_h            = 0
  include_tags         = true
  require_full_window  = false
  new_host_delay       = var.new_host_delay
  notify_no_data       = false
  renotify_interval    = 0
  escalation_message   = ""
  thresholds           = var.pvc_pending_duration_thresholds
  tags                 = local.common_tags
}

resource "datadog_monitor" "trident_slow_operation" {
  name = "Slow Trident Operation in {{cluster.name}}"
  type = "metric alert"
  query = "max(last_5m):max:trident.trident_operation_duration_milliseconds.quantile{quantile:0.99,!operation:volume_delete,!operation:volume_add} by {cluster,operation} > ${var.trident_ops_duration_thresholds.critical}"
  message = <<EOF
  A Trident operation is slower than expected to complete. This could indicate a problem with either Trident or ONTAP and should be investigated.
  
  See the [Dashboard](${var.trident_volumes_dashboard_url}) for more information on the service's status and [Documentation](${var.trident_documentation_url}) for troubleshooting steps.
  
  {{#is_alert}}${join(" ", var.notifications_addresses)}{{/is_alert}}
  {{#is_alert_recovery}}${join(" ", var.notifications_addresses)}{{/is_alert_recovery}}
  EOF
  notify_audit         = false
  locked               = false
  timeout_h            = 0
  include_tags         = true
  require_full_window  = false
  new_host_delay       = var.new_host_delay
  notify_no_data       = false
  renotify_interval    = 0
  escalation_message   = ""
  thresholds           = var.trident_ops_duration_thresholds
  tags                 = local.common_tags
}

resource "datadog_monitor" "trident_slow_vol_create_delete" {
  name = "Slow Trident Volume Create/Delete Operation in {{cluster.name}}"
  type = "metric alert"
  query = "max(last_5m):avg:trident.trident_operation_duration_milliseconds.quantile{quantile:0.99,!operation:volume_get,!operation:volume_list,!operation:backend_list,!operation:backend_get,!operation:storageclass_add,!operation:storageclass_get} by {cluster,operation} > ${var.trident_create_delete_duration_thresholds.critical}"
  message = <<EOF
  A Trident volume create or delete operation is slower than expected to complete. This could indicate a problem with either Trident or ONTAP and should be investigated.
  
  See the [Dashboard](${var.trident_volumes_dashboard_url}) for more information on the service's status and [Documentation](${var.trident_documentation_url}) for troubleshooting steps.
  
  {{#is_alert}}${join(" ", var.notifications_addresses)}{{/is_alert}}
  {{#is_alert_recovery}}${join(" ", var.notifications_addresses)}{{/is_alert_recovery}}
  EOF
  notify_audit         = false
  locked               = false
  timeout_h            = 0
  include_tags         = true
  require_full_window  = false
  new_host_delay       = var.new_host_delay
  notify_no_data       = false
  renotify_interval    = 0
  escalation_message   = ""
  thresholds           = var.trident_create_delete_duration_thresholds
  tags                 = local.common_tags
}
```

synthetics_global_vars
```hcl
data "aws_secretsmanager_secret_version" "platform_ocp_creds" {
  secret_id = "platform/ocp/idm/basic-auth/synthetics-creds"
}

locals {
  plaform_ocp_creds = jsondecode(chomp(data.aws_secretsmanager_secret_version.platform_ocp_creds.secret_string))
}

resource "datadog_synthetics_global_variable" "platform_ocp_pass" {
  name = "PLATFORM_OCP_PASS${terraform.workspace == "pr" ? "_PR" : ""}"
  description = "Platform team password to use when authenticating with IDM"
  tags = ["app:ocp", "team:platform"]
  value = lookup(local.plaform_ocp_creds, "pass")
  secure = true
}

resource "datadog_synthetics_global_variable" "platform_ocp_user" {
  name = "PLATFORM_OCP_USER${terraform.workspace == "pr" ? "_PR" : ""}"
  description = "Platform team username to use when authenticating with OpenShift"
  tags = ["app:ocp", "team:platform"]
  value = lookup(local.plaform_ocp_creds, "user")
}
```

### Debug Output

https://gist.github.com/bkimbrough88/5daa97da87ceae71eea889f3057a17a6

### Panic Output

N/A

### Expected Behavior

Resources should have been provisioned and persisted in TF state

### Actual Behavior

Resources were created, but were not maintained in state

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

**Comment by Nemilar** [comment]
Encountering the same issue, specifically on the `datadog_monitor` resource; we have a codebase that instantiates this resource via a module several times.  It has always worked flawlessly, but as of a few hours ago we consistently hit this error, without any code changes (just calling the same module another time).

**Comment by Nemilar** [comment]
We're no longer hitting this issue.

**Comment by therve** [comment]
Thanks for the report. Could you create a support ticket if that's still happening?

**Comment by judgeaxl** [comment]
I get the same error trying to apply the aws datadog integration in Terraform. This worked only last week though. I'll try to put a ticket together.

**Comment by bkimbrough88** [comment]
I'll create the support ticket

**Comment by therve** [comment]
I believe the situation is resolved. Let us know if you're getting the issue again. Thanks!

**Comment by judgeaxl** [comment]
I still get this in 2.20.0, for datadog_integration_aws. What output/logs would you like me to attach?

**Comment by therve** [comment]
If you have your terraform config that'd be a good start, thanks.

**Comment by judgeaxl** [comment]
Sorry, I read it wrong, it was the `datadog_integration_aws_log_collection` resource. However, that config is even simpler, and `var.log_collection_services` is an empty collection in this case as I haven't configured any yet. The `datadog_integration_aws` was applied earlier, so I don't believe it's a race, although I should probably put a dependency between them, for when I redo this from scratch.

```
resource "datadog_integration_aws_log_collection" "this" {
  account_id = data.aws_caller_identity.this.account_id
  services   = var.log_collection_services
}
```
